# Generated by Django 3.0.4 on 2020-03-23 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('moduleInstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ModuleInstance')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Professor')),
            ],
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='professor',
            field=models.ManyToManyField(to='pages.Professor'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleinstance',
            unique_together={('year', 'semester', 'module')},
        ),
    ]
