# Generated by Django 3.0.4 on 2020-03-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200323_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='module',
            name='id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='module',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='module',
            name='year',
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('module', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.CASCADE, to='pages.Module')),
                ('professor', models.ManyToManyField(to='pages.Professor')),
            ],
            options={
                'unique_together': {('year', 'semester', 'module_id')},
            },
        ),
    ]
